services:
  db:
    image: postgres:16-alpine
    container_name: game24-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - game24_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  migrate:
    image: 24game-aquasorata-server
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
    working_dir: /app/packages/db
    command: >
      sh -c "npm run migrate:deploy"

  server:
    build:
      context: .
      dockerfile: apps/game-server/Dockerfile
    container_name: game24-server
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "4001:4001"
  
  studio:
    image: 24game-aquasorata-server
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BROWSER: none
    working_dir: /app/packages/db
    command: >
      sh -c "npx prisma studio --port 5555"
    ports:
      - "5555:5555"

volumes:
  game24_pgdata: